
language: en
pipeline:
  - name: SpacyNLP
    model: "en_core_web_lg"
    #case_sensitive: True
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
    alias: "spacyfeat"
    #*case_sensitive: False 
    # use lookup tables to extract entities
    #*use_lookup_tables: False
    # use regexes to extract entities
    use_regexes: True
  - name: RegexFeaturizer
    alias: "regexfeat"
  - name: LexicalSyntacticFeaturizer
    alias: "lexfeat"
  - name: CountVectorsFeaturizer
    alias: "countfeat1"
  - name: CountVectorsFeaturizer
    alias: "countfeat2"
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: SpacyEntityExtractor
    # dimensions to extract
    dimensions: ["PERSON"]
  - name: DIETClassifier
    batch_strategy: sequence
    epochs: 100
  - name: EntitySynonymMapper
#Other
  - name: FallbackClassifier
    threshold: 0.3
#Handling faq for ask_amenity
  - name: ResponseSelector
    epochs: 120
    retrieval_intent: ask_amenity
    featurizers: ["spacyfeat","regexfeat","countfeat1","countfeat2"]

policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 4
  epochs: 200
- name: RulePolicy
  # One stage fallback: Confidence threshold for the `core_fallback_action_name` to apply.
  # The action will apply if no other action was predicted with
  # a confidence >= core_fallback_threshold
  core_fallback_threshold: 0.2
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: True